#define FOLDER_NAME "CircuitPython"
#define SOUND_CHANNELS 0

#define NO_ARDUINO 1
#define USE_SDFAT 0
#define CUSTOM_TFT_FUNCTIONS 1
#define CUSTOM_TFT_SPI_FUNCTIONS 1
#define USE_TFT_DESCRIPTORS 0
#define CUSTOM_BUTTON_FUNCTIONS 1
#define USE_PRINTF 0
#define CUSTOM_MALLOC 1
#define AUTOCREATE_OBJECT 0
#define AUTOSHOW_TITLESCREEN 0
#define AUTOSHOW_STARTSCREEN 0
#define NEOPIXELS_ALTERNATIVE_METHOD 1

#define HARDFAULT_DEBUG_HANDLER 1
